### ISSUE TITLE
Parsing annotation field as a promQL expression

### ISSUE THREAD

**Issue by neufeldtech** [FUSAKLA/promruval#2]
Hey there, this tool looks very interesting and it has the potential to solve some issues that we've been experiencing as of late.

In our use-case, we have the need to embed extra promQL expressions in alert annotations for use by other external systems to query against Prometheus. We have the need to validate that these expressions when running builds, but as you know, `promtool` only checks the promQL validity of the `expr` field, and doesn't check other fields like `annotations.meta_query`.

Would you be interested in including a feature in the project like the above as an additional type of rule check? Myself or one of my colleagues would be willing to contribute if it's something you'd consider including in the project.

====

To explain more of our use-case with examples, here is an example alert definition that we have:

```
   - alert: WindowsNodeDiskWillFillIn4Hours
        expr: predict_linear(wmi_logical_disk_free_bytes[2h], 4 * 3600) < 0
        for: 5m
        labels:
          env: prd
        annotations:
          summary: "Node {{$labels.instance}} is predicted to fill its disk in less than 4 hours."
          meta_query: 'count(label_replace(wmi_logical_disk_free_bytes, "host", "$1", "instance", "(.*)")) by(host)'
```

You can see that the `meta_query` is a little different from the `expr` - it's basically for the purpose of a different non-prometheus system 'discovering' what servers are actually exposing this metric to prometheus.

We have the need to ensure that `meta_query` is also a valid promQL expression - i.e. not missing parenthesis, etc.
