### ISSUE TITLE
Support strict unmarshalling of the yaml files

### ISSUE THREAD

**Issue by jmichalek132** [FUSAKLA/promruval#68]
When mimir ruler faces unknown field in the rules yaml files if fails to unmarshall the file and the alerts / rules are not loaded.
Right now promruval doesn't catch this case.

Sample log line from mimir ruler with the error.

```
ts=2024-06-24T07:24:02.015162335Z caller=ruler.go:577 level=error msg="unable to list rules to sync" err="failed to fetch rule groups for user metamonitoring: failed to load rule group for user metamonitoring and namespace mimir-testing.yaml: error parsing /rules-repo/current/rules/metrics/metamonitoring/mimir-testing.yaml: /rules-repo/current/rules/metrics/metamonitoring/mimir-testing.yaml: yaml: unmarshal errors:\n  line 3: field wrong not found in type rulefmt.RuleGroup"
```

Testing yaml file
```yaml
  - name: testGroup
    wrong: true
    rules:
      - alert: test2
        expr: up == 0
        for: 1m
        labels:
          team: "{{ .Labels.team }}"
          xxx: fooo
          severity: critical
        annotations:
          title: test alert
          playbook: http://foo.bar/nonexisting/playbook
```

It would be great if there was a validation option / flag to validate the rules file will pass strict unmarshalling, since there are small differences of what the rules fille looks like between prometheus / mimir / thanos it should be possible specifying which one to validate for.
